[package]
name = "lww-table"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = "0.2.1"
serde = "1.0.197"
serde_json = "1.0.114"
smallvec = "1.13.1"
smol_str = "0.2.1"
